version: "1"
stages:
  success:
    steps:
      - name: success_before
        image: alpine:latest
        commands:
          - echo "SUCCESS"
        ruleset:
          status: [ success ]
      
      - name: empty
        image: alpine:latest
        commands:
          - echo "EMPTY"   
          
  success_failure:
    steps:
      - name: success_failure
        image: alpine:latest
        commands:
          - echo "SUCCESS OR FAILURE"
        ruleset:
          status: [ success, failure ] 

  failure_before:
    steps:
      - name: failure_before
        image: alpine:latest
        commands:
          - echo "FAILURE BEFORE"
        ruleset:
          status: [ failure ]         
    
  echo:
    needs: [ success, success_failure, failure_before ]
    steps:
      - name: echo
        image: alpine:latest
        commands:
          # - echo "hi"
          - eco "hi"
        ruleset:
          status: [ success ]
    
  after:
    needs: [ echo ]
    steps:
      - name: success_after
        image: alpine:latest
        commands:
          - echo "SUCCESS"
        ruleset:
          status: [ success ]
    
      - name: failure
        image: alpine:latest
        commands:
          - echo "FAILURE"
        ruleset:
          status: [ failure ]  

  failure_master:
    needs: [ echo ]
    steps:
      - name: failure_master
        image: alpine:latest
        commands:
          - echo "MASTER FAILURE"
        ruleset:
          branch: master
          event: [ push ]
          status: [ failure ]     
      
  success_failure_2:
    needs: [ failure ]
    steps:
      - name: success_failure
        image: alpine:latest
        commands:
          - echo "SUCCESS OR FAILURE"
        ruleset:
          status: [ success, failure ] 