version: "1"

stages:
  success_before:
    steps:
      - name: success_before
        image: alpine:latest
        commands:
          - echo "SUCCESS"
        ruleset:
          status: [ success ]

  echo:
    steps:
      - name: echo
        image: alpine:latest
        commands:
          # - echo "hi"
          - eco "hi"
        ruleset:
          status: [ success ]
      - name: success_after
        image: alpine:latest
        commands:
          - echo "SUCCESS"
        ruleset:
          status: [ success ]
      - name: failure
        image: alpine:latest
        commands:
          - echo "FAILURE"
        ruleset:
          status: [ failure ]
    
  failure:
    need: [ echo, success_before ]
    steps:          
      - name: failure
        image: alpine:latest
        commands:
          - echo "FAILURE"
        ruleset:
          status: [ failure ]   